### ISSUE TITLE
关于fork改名之后

### ISSUE THREAD

**Issue by iyongliang** [fengzhichu/fengzhichu-theme#12]
我fork改名之后，github.io页面加载没有js和css，查看firebug，所有的静态文件前面任然有fengzhichu-theme/js类似这种

**Comment by fengzhichu** [comment]
你好，感谢你 fork fengzhichu-theme，我看了你的主页，url中依然有/fengzhichu-theme/，应该是修改了gh-pages分支下的_config.yml，没有修改master分支下的_config.yml，github.io加载的是master分支的页面，普通项目加载gh-pages。抱歉，我没有在README中说清楚。
