### ISSUE TITLE
How to make the dates to appear in English?

### ISSUE THREAD

**Issue by vicrucann** [fengzhichu/fengzhichu-theme#16]
Nice theme, but would be nice if I could change non-English words into English.

**Comment by fengzhichu** [comment]
1. Open the _.md file in ' fengzhichu-theme / blog / category ' , and replace ' *_title*\* ' with English words. 
2. Open three html files in ' _layouts ' , **post.html** and **blog_by_tag.html** and **blog_by_category.html**, you can change the time format like ' %-d/%m/%Y ' at line 15 and line 24 and line 24.

**Comment by vicrucann** [comment]
Thank you!
