### ISSUE TITLE
fork了，但是加载不出样式

### ISSUE THREAD

**Issue by chihane** [fengzhichu/fengzhichu-theme#8]
http://mlxy.github.io/
像这样……

**Comment by fengzhichu** [comment]
你需要设置 '_config.yml' ，把 baseurl 设置为空。

``` yml
baseurl: ""
```

**Comment by chihane** [comment]
已经清空了，但是问题 依旧。
而且对title的修改也没有生效……
是不是还有哪里要修改我没注意到的？
https://github.com/mlxy/mlxy.github.io/blob/gh-pages/_config.yml

**Comment by fengzhichu** [comment]
明天我clone你repo，调试一下

**Comment by fengzhichu** [comment]
你好，我把你的网站clone下来编译了，一切正常，样式都可以加载，_config.yml中的其他调整也都应用了。你再看一下是不是其他地方的配置有问题。

**Comment by chihane** [comment]
我本地跑`jekyll serve --w`一直不成功，redcarpet装不上。查了下好像跟jekyll版本有关，你用的是什么版本？
另外本地跑通和github-pages好像又是两回事，我看你的博客也是直接挂在git上的，就一切正常，也不知道是哪里不一样了……

# 

直接fork了博客就正常了，对config的修改也可以即时反馈。是不是从模板那个repo到博客之间还要做什么操作？

# 

于是我直接在你的博客基础上修改了，希望你不要介意……页面底部也附加了主题的版权信息
找了不少主题，还是觉得你这个比较好看，在提issue之前自己已经折腾了好几天了……

**Comment by fengzhichu** [comment]
嗯，没事，也可能是我的主题哪里有问题，我还没发现，这两天研究一下。另外，我用的ruby版本是 2.2.3p173，jekyll版本是 2.5.3 。
